name: "CI"

on:
  push:
    paths-ignore:
      - "docs/**"
    branches:
      - master
    tags:
      - snapshot
      - v*
  pull_request:

jobs:
  test:
    name: Tests
    uses: ./.github/workflows/tests.yml

  release:
    name: Release
    uses: ./.github/workflows/release.yml
    needs: test
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  automerge:
    name: Auto-merge
    uses: ./.github/workflows/automerge.yml
    needs: release
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

# vim:ft=yaml:et:ts=2:sw=2
