on:
  workflow_call:
    secrets:
      github-token:
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout eventum/eventum code
        uses: actions/checkout@v3

      - name: Set version variable
        id: vars
        run: |
          echo "GITHUB_REF=$GITHUB_REF"
          if [[ "${GITHUB_REF#refs/tags/v}" != "${GITHUB_REF}" ]]; then
            APP_VERSION=${GITHUB_REF#refs/tags/v}
          else
            git fetch origin --unshallow "+refs/tags/v*:refs/tags/v*"
            version=$(git describe --tags --abbrev=9 --match="v*")
            APP_VERSION=${version#v}
          fi
          echo "version=$APP_VERSION"
          echo "version=$APP_VERSION" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build release tarball
        uses: docker/build-push-action@v3
        env:
          APP_VERSION: ${{ steps.vars.outputs.version }}
        with:
          context: .
          file: bin/releng/Dockerfile
          build-args: |
            APP_VERSION=${{ env.APP_VERSION }}
          platforms: linux/amd64
          target: out
          outputs: |
            type=local,dest=out

      - name: Compress release
        run: |
          mv out/eventum-*.tar .
          ls -lh eventum-*.tar
          xz -9e eventum-*.tar
          ls -lh eventum-*.tar.xz

      # https://github.com/actions/upload-artifact
      - uses: actions/upload-artifact@v3
        with:
          name: eventum
          path: eventum-*.tar.xz
          # 'warn' or 'ignore' are also available, defaults to `warn`
          if-no-files-found: error

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}

      - name: Checkout eventum/docker code
        uses: actions/checkout@v3
        with:
          repository: eventum/docker
          path: docker

      - name: Prepare tarball for Docker build
        run: |
          ln eventum-*.tar.xz docker

      - name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: docker
          load: true
          build-args: |
            BUILDTYPE=local
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: |
            type=docker,dest=eventum-docker-${{ steps.vars.outputs.version }}.tar

      - uses: actions/upload-artifact@v3
        with:
          name: docker-${{ steps.vars.outputs.version }}
          path: eventum-docker-*.tar
          if-no-files-found: error

  publish:
    name: Create Release
    runs-on: ubuntu-20.04
    needs: build
    permissions:
      contents: write

    steps:
      - name: Checkout eventum/eventum code
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: eventum

      - name: Generate Release notes
        if: github.ref == 'refs/tags/snapshot' || startsWith(github.ref, 'refs/tags/v')
        run: |
          # Extract message from the tag
          # https://stackoverflow.com/a/63583775/2314626
          tag=${GITHUB_REF#refs/tags/}
          echo "Release notes from '$tag' tag"
          git fetch origin --unshallow "+refs/tags/*:refs/tags/*"
          git tag -l --format='%(contents)' $tag | tee RELEASE_NOTES.md

      - uses: ncipollo/release-action@v1
        if: github.ref == 'refs/tags/snapshot' || startsWith(github.ref, 'refs/tags/v')
        env:
          SNAPSHOT: ${{ github.ref == 'refs/tags/snapshot' }}
          RELEASE: ${{ github.ref != 'refs/tags/snapshot' }}
        with:
          allowUpdates: ${{ env.SNAPSHOT }}
          artifacts: eventum-*.tar.xz
          replacesArtifacts: false
          omitBody: ${{ env.RELEASE }}
          generateReleaseNotes: ${{ env.RELEASE }}
          bodyFile: RELEASE_NOTES.md
          token: ${{ secrets.github-token }}
          prerelease: ${{ env.SNAPSHOT }}

# vim:ft=yaml:et:ts=2:sw=2
